version: "3"
services:
    client:
        restart: always
        container_name: vps-client
        image: nginx
        ports:
            - 3005:80
        volumes:
            - ./:/usr/share/nginx/html

